import { json, type RequestHandler } from '@sveltejs/kit'

export const GET: RequestHandler = async () => {
    // get articles from datasource
    // const articles = [
    //     {
    //         title: 'Article 1',
    //         content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl eget ultricies aliquam, nunc nisl aliquet nunc'
    //     },
    // ]

    // get articles from datasource in unsplit text format
    const articles = [
        {
            body: `Local Man Excited to Finally Use Geology Degree, Finds Job Rock-Solid#
            After years of struggling to find a use for his geology degree, local man Jack Sanders was finally able to land a job in his field of study. Sanders, who graduated from the University of Michigan in 2014, had been unable to find work that utilized his degree and had been working as a bartender ever since. However, after months of tireless searching, Sanders was able to secure a job as a geologist for a local mining company, and he could not be more excited. "I feel like a weight has been lifted off of my shoulders," Sanders said. "I've been waiting for so long to actually use my degree, and now I'm finally getting the chance. It feels rock-solid." Sanders' new job will require him to analyze rock formations and assess the potential value of various minerals. While some may find this type of work boring or tedious, Sanders is thrilled to finally be doing something that he is passionate about. "I've always loved rocks," Sanders explained. "Ever since I was a kid, I've been collecting them and studying them. Now, I get to do that for a living. It's a dream come true." Sanders' coworkers have also been impressed with his enthusiasm and knowledge of geology. According to his boss, Sanders has already made a significant impact on the company. "Jack is a real asset to our team," said Steve Johnson, the head geologist at the mining company. "He brings a level of passion and expertise to the job that is truly invaluable. Plus, he's just a great guy to work with." While some may be surprised that Sanders was able to find a job in his field of study, he says that it was just a matter of persistence and determination. "I never gave up on my dream of working in geology," Sanders said. "Even when things seemed bleak, I knew that if I kept trying, something would eventually come along. And it did." Sanders hopes that his story will inspire others who are struggling to find work in their chosen field. "I want people to know that it's never too late to pursue your passion," Sanders said. "If you keep working hard and don't give up, you can achieve anything." With his dream finally realized, Sanders is looking forward to a long and fulfilling career in geology. Who knows, he might even find the next big mineral deposit.`
        },
        {
            body: `Man Who Always Orders Water At Restaurants Surprised To Learn He's Still Alive#
            According to sources close to local man Daniel Peterson, who has always ordered water without exception whenever he dines out, was recently surprised and relieved to discover that he is still alive. "I was at the doctor's office for a routine checkup when he told me that I was in remarkably good health," said Peterson. "I was like, 'Really? Even though I always order water at restaurants?' And he was like, 'Yes, your choice of beverage has absolutely no bearing on your overall health.' I was so relieved!" Peterson has reportedly been a staunch supporter of drinking water while dining out, citing its health benefits and the financial savings it provides. However, he never imagined that it would have such a profound impact on his well-being. "I always thought that drinking soda or alcohol with my meals would surely catch up with me eventually," said Peterson. "But now I know that I can continue to order water and be just as healthy as anyone else. It's a huge weight off my shoulders." Despite his newfound sense of relief, Peterson admits that he has faced some social stigma for his beverage choice over the years. "People have always looked at me weird when I order water," said Peterson. "They assume that I'm some kind of health nut or that I'm too cheap to order something else. But I'm just trying to do what's best for my body and my wallet." Peterson's friends and family have also been surprised by his healthy checkup and are now reconsidering their own beverage choices. "I always thought Dan was a little crazy for only drinking water at restaurants," said Peterson's friend, Jeff. "But now that I know he's still alive, maybe he's onto something. I might have to start following his lead." Despite the newfound attention, Peterson maintains that his decision to always order water is a personal one that he will not be swayed from. "I'm not trying to convert anyone to Team Water or anything," said Peterson. "I just know what works for me, and that's all that matters."`
        },
        {
            body: `Local Man Shocked to Discover He is Not the Main Character in His Own Life#
            In a startling revelation, 34-year-old Frank Johnson of Peoria, Illinois has recently come to the realization that he is not, in fact, the main character in his own life. "I always assumed that I was the protagonist," Johnson said. "But now, looking back, I can see that I'm more of a supporting character." Johnson, who works as an accountant and enjoys watching sports, going to movies, and hanging out with his friends, said that he didn't notice the signs at first. "I thought that my life was pretty good," he said. "I had a steady job, a nice apartment, and some great relationships. But then one day I was walking down the street and I saw a billboard for a movie that looked really interesting, and I realized that I wasn't the one on the poster. I wasn't the one who the story was about." Johnson said that this realization has had a profound impact on him. "It's like, what am I even doing here?" he said. "If I'm not the main character, then what's my purpose? Am I just here to provide exposition or comedic relief?" Johnson's friends and family have been supportive, but some have expressed concern that he's taking this too seriously. "Frank's a great guy, and we all love him," said his friend Dave. "But I don't think he needs to worry so much about being the main character. I mean, life isn't a movie." But Johnson disagrees. "I think Dave just doesn't get it," he said. "I mean, sure, life isn't a movie. But it could be. And if it were, I want to be the main character." Johnson has started to make changes to his life in order to become more of a protagonist. "I'm trying to be more adventurous," he said. "I'm signing up for salsa dancing classes and I'm planning a trip to Europe. I want to have interesting experiences that I can talk about later." Johnson has also started a blog to document his journey. "It's called 'The Frank Johnson Experience'," he said. "It's all about how I'm trying to become the main character in my own life. I think people will really relate to it." Only time will tell whether Johnson's quest for protagonist status will be successful, but for now, he's determined to make the most of his supporting role. "I'm going to be the best supporting character I can be," he said. "And who knows? Maybe one day I'll get my own spin-off."`
        },
        {
            body: `Local Man Shocked to Discover His Entire Life Has Been a Reality Show#
            Schenectady, NY - In a stunning turn of events, local resident Tom Johnson was recently informed that his entire life has been secretly filmed and broadcasted as a reality show. Johnson, 43, had no idea that his every move, conversation, and action had been captured on camera and aired to millions of viewers around the world. Johnson, who thought he was living a normal, unremarkable life, was in complete shock when he was approached by a group of producers from the network that had been broadcasting his life for the past 20 years. According to the producers, Johnson was chosen as the subject of the show because of his ordinary life and lack of any appeal whatsoever. "I couldn't believe it when they told me," Johnson said in a recent interview with The Onion. "I mean, I knew my life was boring, but I didn't think it was so boring that it warranted a TV show." The show, titled "The Life of Tom Johnson," had been on the air for two decades and has a cult following among viewers who enjoy watching Johnson go about his day-to-day life. According to the show's producers, the most exciting episode to air featured Johnson grocery shopping for two hours. Johnson's friends and family were also shocked to learn about the show, which they had no idea existed. "I just can't believe I've been on TV for 20 years without knowing it," Johnson's wife said. "I mean, I thought I was just living a normal life with my husband, but it turns out we were stars of a boring TV show." The revelation has left Johnson feeling violated and less secure about his privacy. "I just don't know who has been watching me and what they've been doing with all that footage," Johnson said. "I mean, it's not like I did anything exciting or interesting. So why would anyone want to watch me?" Despite the shock and confusion surrounding the situation, Johnson has reportedly signed a contract to continue filming "The Life of Tom Johnson" for another 10 years. "I figure if people really want to watch me do nothing, who am I to deny them?" Johnson said. The producers of the show have expressed excitement about the future of "The Life of Tom Johnson" and have reportedly planned a special episode where Johnson takes a nap for three hours straight. Viewers can expect the episode to air sometime next month. In a world where reality TV has become increasingly outrageous and dramatic, "The Life of Tom Johnson" offers a refreshing change of pace. Viewers can tune in to watch a man live a completely ordinary life without any of the excitement or drama that has come to define reality TV. And as long as Tom Johnson continues to lead a dull and unremarkable life, there will always be an audience eager to tune in and watch.`
        },
        {
            body: `Man Who Hasn't Seen The Sun In 10 Years Shocked To Learn It's Still There#
            PHOENIX, AZ - Ron Johnson, a 37-year-old software engineer, was shocked to learn that the sun, a giant ball of gas in the sky, is still shining despite his 10-year streak of never seeing it. "I just assumed it had gone out or something," Johnson said in an interview, "I mean, I never see it, so I just assumed it wasn't there." Johnson, who spends most of his days sitting in front of a computer, rarely ventures outside during the daylight hours. He said that he only ever sees the sun when he accidentally wakes up early or procrastinates long enough to be working outside during daylight hours. "I guess I just never really thought about it," Johnson said, "I mean, I know I should probably go outside more, but Netflix is just so much easier." Johnson went on to say that he was very surprised to learn that the sun still exists and that it was still a giant ball of gas in the sky. "I mean, I thought maybe it was still around, but I didn't realize it was still a giant ball of gas in the sky," Johnson said, "that's pretty wild." Johnson's coworkers were quick to make fun of him when they learned about his lack of sun exposure. "I mean, we all work in Phoenix," coworker Brittany Parker said, "how do you not see the sun? It's literally everywhere." Johnson said that he plans to make an effort to go outside more frequently from now on, but he's not entirely sure where to start. "I guess I'll just start by going outside for a walk or something," Johnson said, "I mean, I have to start somewhere." Despite Johnson's lack of sun exposure, doctors say that he's still relatively healthy. However, they do recommend that he spends more time outside in order to get some much-needed vitamin D. "Sun exposure is really important for overall health," Dr. Lisa Rodriguez said, "I would definitely recommend that he tries to spend more time outside." With this newfound knowledge, Johnson plans to spend more time outside and maybe even go on a vacation to somewhere with a lot of sunshine. "I think I'm definitely due for a vacation somewhere sunny," Johnson said, "I mean, I have some catching up to do."`
        },
        {
            body: `Local Man Excels at Procrastination, Wins Lifetime Achievement Award#
            Cedar Rapids, IA - In a stunning turn of events, local man Tim Smith is being recognized for his exceptional skills in procrastination. Smith, a 36-year-old graphic designer, has been awarded the prestigious Lifetime Achievement Award for Procrastination by the National Society of Procrastinators. The award, which is given annually to an individual who has demonstrated unparalleled ability in avoiding tasks, was presented to Smith at a ceremony held at the society's headquarters in New York City. In his acceptance speech, Smith expressed his gratitude for the recognition, and spoke about his lifelong love of putting things off. "I want to thank the National Society of Procrastinators for this incredible honor," said Smith, who was visibly moved. "I've been procrastinating for as long as I can remember, and it's really nice to know that all my hard work has paid off." Smith's impressive resume of procrastination includes putting off laundry for weeks at a time, waiting until the last minute to file his taxes, and delaying the completion of a major design project until the day before it was due. He has also been known to put off grocery shopping until there's nothing left in the fridge but expired milk and moldy bread. When asked about his secrets to success, Smith cited his ability to distract himself with social media, cat videos, and online shopping. "I'm really good at finding ways to waste time," he said with a laugh. "It's like a superpower, but less useful." Despite his many accomplishments, Smith admitted that there have been times when his procrastination has gotten the best of him. He recounted a recent incident where he put off renewing his driver's license until the day it expired, only to find out that the DMV was closed for a holiday. "I had to ride my bike to work for a week because of that," he said ruefully. "But hey, it was still worth it." Smith's colleagues were quick to congratulate him on his award, with many expressing their admiration for his ability to get things done at the last minute. "He's a master at putting things off until the very end, and then somehow managing to get it all done on time," said coworker Sarah Johnson. "It's really quite impressive." As for Smith himself, he said that he plans to continue honing his procrastination skills for years to come. "There's always room for improvement," he said. "And who knows, maybe someday I'll be inducted into the procrastination hall of fame."`
        },
        {
            body: `Local Man Finally Cleans Out Fridge, Discovers New Form of Life#
            Jacksonville, FL - After months of procrastination, local resident Doug Peters finally decided it was time to clean out his refrigerator. What he found inside was not what he was expecting. Peters, who had been ignoring the growing pile of expired condiments and wilted produce, finally had enough when he opened the door to a foul smell that had been developing for weeks. He rolled up his sleeves and prepared to tackle the project, fully expecting to find nothing but moldy leftovers and expired milk. But as he began to remove items from the fridge, Peters noticed something strange. In the back of the fridge, he discovered what appeared to be a new form of life. "At first I thought it was just some sort of mold or fungus, but the more I looked at it, the more I realized it was something else entirely," Peters said. The organism, which Peters dubbed "Fridgus Maximus," appeared to be a blob-like creature with multiple tentacles and a translucent body. Peters tried to touch it with a fork, but the creature seemed to recoil in fear and retreated further into the depths of the fridge. "I didn't know what to do at first," Peters said. "I mean, do I try to capture it? Call a scientist? Sell it to the highest bidder?" Peters eventually decided to document his discovery and posted photos of the creature on social media. The images quickly went viral, with people around the world speculating on what the creature might be and how it came to be in Peters' fridge. Scientists were particularly interested in the find, with several reaching out to Peters to request a sample of the creature for further study. "I've never seen anything like this before," said Dr. Sarah Thompson, a leading microbiologist. "It's possible that this is a completely new form of life that we've never encountered before. This could be a major scientific breakthrough." As for Peters, he's still trying to come to terms with his newfound fame. "I never thought that cleaning out my fridge would lead to all of this," Peters said. "Who knows what else is lurking in there? Maybe I need to start cleaning more often." For now, Peters has decided to leave Fridgus Maximus alone, hoping that scientists will be able to learn more about the mysterious creature and its origins. "I feel like I've discovered something truly amazing," Peters said. "Who knows what else is out there waiting to be found?"`
        },
        {
            body: `Local Man Discovers the Ultimate Hack to Avoid Small Talk with Acquaintances#
            As a society, we've been conditioned to make small talk. It's a universal experience that's all but guaranteed to surface in nearly every public interaction. From the barista at your coffee shop to the distant cousin you see twice a year at family gatherings, we're all guilty of engaging in the same mundane conversations over and over again. But what if there was a way to avoid this? A solution that would spare us the time and energy of engaging in yet another talk about the weather or the latest Netflix series? Enter local man, John, who claims to have the ultimate hack to avoid small talk with acquaintances. John has been using this method for over a year now and swears by its effectiveness. In an exclusive interview with The Onion, he shared his secret with us. "It's really quite simple," John began, "Whenever I run into someone I don't really feel like talking to, I just pretend to have a phone call. I'll take out my phone, put it on speaker, and start talking as if I'm in the middle of an important conversation. Works every time." But what happens if the person tries to say hi or interrupt John mid-conversation? "I just nod my head and keep talking," he replied. "It's important to stay in character, you know?" John isn't the only one to have discovered the joys of pretending to have a phone call. In fact, this practice has become so widespread that there are even apps available now that create fake phone calls in case you don't want to use your real one. It's a trend that embodies the age-old adage of 'fake it until you make it.' But not everyone is a fan of this new approach to avoiding small talk. Alice, a 27-year-old marketing professional, thinks that it's "rude and disingenuous" to pretend to be on the phone just to avoid talking to someone. "I understand not wanting to engage in small talk all the time, but there are better ways to handle it than pretending to be on the phone," she said. So, is pretending to have a phone call really the ultimate hack to avoid small talk? It's certainly a divisive issue, but one thing is for sure: it's a trend that's here to stay. Whether we like it or not, more and more people are turning to this approach to avoid small talk, and it's only a matter of time before it becomes an accepted social norm. In conclusion, if you find yourself dreading yet another conversation about the weather with your friendly neighborhood barista, perhaps it's time to take a page out of John's book and pretend to be on the phone. After all, as John himself puts it, "It's not lying if you're doing it to protect your own sanity."`
        },
        {
            body: `Local man spends entire workday refreshing fantasy football app#
            A local man has reportedly spent his entire workday refreshing his fantasy football app, according to sources. The man, identified as Greg Johnson, has allegedly not completed any work-related tasks since arriving at the office this morning, instead opting to obsessively check and refresh his fantasy football app. “I can’t help it,” Johnson reportedly told coworkers. “I’m in three different leagues and I’ve got a lot of money riding on this season.” Johnson’s coworkers are said to be growing increasingly frustrated with his behavior, as his constant phone checking and distractedness are slowing down the team’s productivity. “We’ve got deadlines to meet and Greg is just sitting there, scrolling through his lineup,” said one exasperated coworker. Despite the complaints from his colleagues, Johnson seems determined to continue his fantasy football obsession. “I’ve got to stay on top of my team, you know? I’ve got to make sure I’m making the right trades and setting the right lineup. This is serious business.” When pressed on how his obsession with fantasy football is affecting his work, Johnson becomes defensive. “Look, I’m doing just fine. I’ve got everything under control. Besides, it’s not like I’m the only one in the office distracting myself with something.” However, sources confirm that Johnson is, in fact, the only employee at the office currently engrossed in a non-work-related activity. “Honestly, it’s kind of impressive how little work he’s able to get done while still managing to keep up with his fantasy football,” said another coworker. “I mean, I’ve got to give him credit for that.” At press time, Johnson was seen celebrating in the break room after his fantasy football quarterback threw a game-winning touchdown pass. “I knew I had a good feeling about him,” he exclaimed, much to the chagrin of his coworkers.`
        },
        {
            body: `Impressive: Man Successfully Avoids Doing Laundry for Fifth Straight Month#
            New York City - In a feat of impressive laziness, local man Jake Harrison has successfully avoided doing laundry for the fifth straight month. “It’s all about strategy,” Harrison told reporters. “If you wear a shirt for two hours while you Netflix and chill, it’s not dirty enough to wash. Just hang it back up and wear it again tomorrow.” Harrison admits that his wardrobe choices have become somewhat limited, but he doesn’t seem to mind. “I mostly stick to dark clothes like black t-shirts and grey sweatpants,” he said. “And I’ve had to get creative with stains. If I spill something on my shirt, I just turn it inside out.” Friends and family members have expressed concern for Harrison, but he assures them that he’s doing just fine. “My mom tried to wash my clothes when she visited last month, but I made her stop,” he said. “She doesn’t understand my lifestyle.” Harrison’s apartment has become a key part of his strategy. He only wears clothes in the living room, and if he needs to use the bathroom, he strips down to his underwear first. “I don’t want to accidentally contaminate any clean clothes,” he explained. Harrison’s roommate, Matt, has had to deal with the smell of unwashed clothes for months. “It’s not great,” Matt said. “But I’m just glad he’s not leaving dirty dishes around anymore.” Harrison’s laziness has also extended to other areas of his life. He hasn’t gone grocery shopping in weeks and has been surviving on a diet of cereal and frozen pizza. “It’s not ideal, but it’s cheap and easy,” he said. Despite his successes, Harrison admits that he’s not sure how much longer he can go without doing laundry. “I’m running out of clothes,” he said. “But I’m hoping I can make it through the winter.” For now, Harrison is content with his minimalist lifestyle. “Honestly, it’s kind of liberating,” he said. “I don’t have to worry about keeping up with fashion trends or making sure my clothes match. I just wear what I want.” But if you happen to be sitting next to Harrison on the subway, you might want to hold your nose.`
        },
        {
            body: `Local Man Who Pronounces 'GIF' With Hard 'G' Declared Public Enemy Number One#
            In a town where the local dialect is known for its nasally twang and dropped "R"s, one man's pronunciation of a three-letter word has caused quite the uproar. Meet Robert Johnson, a self-proclaimed tech enthusiast and graphic designer who has been deemed "Public Enemy Number One" by his fellow townspeople due to his insistence on pronouncing "GIF" with a hard "G." "I just don't understand why people get so worked up over it," says Johnson. "It's not like it's a life or death situation." But for the residents of this small town, it may as well be. Local business owner, Sarah Thompson, has even gone as far as banning Johnson from her coffee shop due to his controversial pronunciation. "He would come in every day and order a 'GIF' latte," says Thompson. "It was like nails on a chalkboard for me and my customers." The debate over the proper pronunciation of "GIF" has been ongoing since the creation of the file format in the 1980s. The creators of the format have stated that it should be pronounced with a soft "G" like "jif," but that hasn't stopped people like Johnson from defying convention. Johnson, however, is not deterred by the backlash. "I think people just need to accept that language is constantly evolving," he says. "Who's to say that my way is any less correct than the so-called 'correct' way?" But for the residents of this small town, it's not just about "correct" versus "incorrect" pronunciation. It's a matter of identity and pride. "We've always pronounced it with a soft 'G'," says longtime resident, Tom Peters. "It's just how we do things here. We don't want outsiders coming in and changing our way of life." The debate over the proper pronunciation of "GIF" has even divided families. "I can't even talk to my brother anymore," says Mary Johnson, Robert's sister. "Every time he says 'GIF' with a hard 'G,' I just want to scream." The local government has even gotten involved, with the mayor declaring a public hearing on the matter next month. "What's next, people pronouncing 'meme' like 'me-me' instead of 'meem'?" says the mayor. "We need to nip this in the bud before it gets out of control." For Johnson, the attention has been overwhelming, but he's not backing down. "I may be the most hated man in town, but at least I'm staying true to myself," he says. "And who knows, maybe one day the rest of the world will catch up to me." But for now, the residents of this small town will continue to cringe every time Johnson says the word "GIF" with a hard "G."`
        },
        {
            body: `Study Finds Majority of Americans Would Rather Go to Dentist Than Attend Another Zoom Meeting#
            As the COVID-19 pandemic drags on, many Americans are finding themselves glued to their computer screens for hours on end attending virtual meetings with coworkers, friends, and family members. But a new study has found that the vast majority of Americans would rather endure a trip to the dentist than sit through another Zoom meeting. The study, conducted by the research firm ZoomMiserable, surveyed over 10,000 Americans about their feelings regarding virtual meetings. The results were clear: 87% of respondents said they would rather undergo a dental procedure than attend another Zoom meeting. "I mean, I'm not a fan of the dentist by any means, but at least it's over quickly," said Sarah Johnson, a marketing manager from Chicago. "These Zoom meetings just go on and on, and you can't even tell if anyone is paying attention." Other respondents cited a variety of reasons for their Zoom fatigue, including technical difficulties, awkward silences, and the difficulty of reading social cues through a screen. "I feel like I'm constantly talking over people or accidentally muting myself," said Dave Martinez, an IT consultant from Seattle. "It's just a total nightmare." The study also revealed some interesting demographic trends. Women were more likely than men to say they would rather go to the dentist, while younger people were more likely to prefer Zoom meetings. "Maybe it's because younger people are more used to communicating through screens," said Dr. Rachel Wagner, a psychologist who was not involved in the study. "Or maybe they just haven't had as many bad experiences with virtual meetings yet." The study has prompted some companies to reevaluate their virtual meeting policies. Some have started offering "Zoom-free" days, while others have implemented shorter meeting times and more frequent breaks. "We want our employees to be productive, but we also don't want to drive them insane," said Tom Sanders, a human resources manager at a tech company in San Francisco. "We're trying to find a balance." Despite these efforts, many Americans remain skeptical that virtual meetings will ever truly replace in-person interaction. "I miss actually being able to read people's body language and see their facial expressions," said Johnson. "Plus, you can never really tell if someone is wearing pants on Zoom." For now, it seems that Zoom meetings are here to stay. But at least we can all take comfort in the fact that most of us would rather have a cavity filled than sit through another one.`
        },
        {
            body: `Local Woman Shocked to Discover Kale Actually Tastes Like Literal Garbage#
            A local woman was reportedly shocked to discover that kale, a leafy green vegetable that has been praised for its health benefits, actually tastes like "literal garbage." Samantha Johnson, 29, had previously heard about the trend of eating kale and decided to give it a try. She had heard that it was packed with vitamins and minerals and was supposed to be a great addition to any healthy diet. "I was excited to try it," she said. "I had seen all these recipes online that made it look delicious." Johnson decided to start by making a kale salad, using a recipe she found online. The recipe called for kale, lemon juice, olive oil, and a mixture of nuts and seeds. "I took one bite and almost gagged," she said. "It was like eating a mouthful of dirt and sadness." Despite the unpleasant taste, Johnson persisted, trying kale in a variety of different dishes. She made kale chips, sautéed kale, and even tried blending it into smoothies. "Nothing worked," she said. "It always tasted like I was eating a clump of grass." Johnson's experience with kale is not unique. Many people have found that the taste of kale is too bitter or earthy for their liking. However, the health benefits of kale cannot be ignored. Kale is rich in vitamins A, C, and K, as well as calcium and fiber. "I really wanted to like kale," Johnson said. "But I just can't get over the taste." In an effort to make kale more palatable, Johnson has started experimenting with different ways to prepare it. She has tried roasting it with garlic and seasoning, adding it to soups, and even hiding it in her spaghetti sauce. "I'm not giving up yet," she said. "I know there must be a way to make kale taste good." Johnson's experience with kale has been a learning experience, and she encourages others to try new foods as well. "You never know what you might like until you try it," she said. "But if you do try kale and hate it, just know that you're not alone."`
        },
        {
            body: `Local Man Outraged After Discovering His Recycling Was Actually Just Being Thrown in the Trash#
            In a stunning revelation, local man David Johnson discovered that his carefully separated recycling was not being recycled at all, but rather just thrown straight into the garbage. Johnson, who describes himself as a "dedicated recycler", was outraged at the news. "I can't believe it. I thought I was doing my part for the environment by recycling, but it turns out it was all for nothing. I might as well have just thrown my plastic bottles and cardboard boxes straight into the trash," said Johnson. According to sources, Johnson's recycling was being collected by a new garbage company that had just started servicing his area. The company, who shall remain nameless, reportedly did not have a separate recycling program and simply dumped all collected waste into the same truck. Johnson's frustration is not uncommon, as more and more people are becoming conscious of the importance of recycling and the impact it has on the environment. The incident has led to calls for stricter regulations and better oversight of garbage companies to ensure that they are properly recycling waste. "This is a wake-up call for all of us. We need to demand better from our garbage companies and hold them accountable for their actions. The planet is at stake here," Johnson said. Despite the disappointment, Johnson remains committed to recycling and says he will continue to do his part for the environment. "I might not be able to trust my garbage company, but I still believe in the importance of recycling. It's up to all of us to make a difference," he said. As for the company responsible for Johnson's wasted recycling, they have yet to comment on the matter.`
        }
    ]
    return json(articles)
}